# Generated by Django 5.0.2 on 2024-02-27 01:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlistings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlistings',
            name='guidename',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
