# Generated by Django 5.0.2 on 2024-03-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='offering_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='offering_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='offering_image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='offering',
            name='offering_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='offering',
            name='offering_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
