# Generated by Django 5.0.2 on 2024-03-17 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main_app.comment'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='availability_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='offering',
            name='availability_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='offering',
            name='host_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='main_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='offering_type',
            field=models.CharField(choices=[('accomodation', 'Accomodation'), ('sight-seeing', 'Sight-seeing'), ('food-tour', 'Food-tour'), ('ride-share', 'Ride-Share')], default='accomodation', max_length=20),
        ),
        migrations.AlterField(
            model_name='offering',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main_app.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
