# Generated by Django 5.0.3 on 2024-03-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('offering', 'user'), name='unique_rating'),
        ),
    ]
