# Generated by Django 5.0.2 on 2024-03-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_loginsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsession',
            name='logged_at',
            field=models.DateTimeField(),
        ),
    ]
