# Generated by Django 4.1.13 on 2024-03-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_loginsession_logged_at'),
        ('main_app', '0003_feedback'),
    ]

    operations = [
    ]
