# Generated by Django 4.1.13 on 2024-03-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_merge_0003_alter_loginsession_logged_at_0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
